spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true

jwt:
  secret: ${JWT_SECRETKEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 720

logging:
  level:
    root: info

sentry:
  dsn: ${SENTRY_DSN} # 환경변수로 추가  
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true